model:
  name: 'hacnn'

data:
  type: 'image'
  sources: ['cuhk03']
  targets: ['cuhk03']
  height: 160
  width: 64
  combineall: False
  transforms: []
  save_dir: 'log/hacnn'

loss:
  name: 'softmax'
  softmax:
    label_smooth: True

train:
  optim: 'adam'
  lr: 0.0005
  max_epoch: 150
  batch_size: 32
  fixbase_epoch: 10
  open_layers: ['classifier_global']
  lr_scheduler: 'single_step'
  stepsize: [300]

test:
  batch_size: 300
  dist_metric: 'euclidean'
  normalize_feature: False
  evaluate: False
  eval_freq: -1
  rerank: False